#spring.profiles.active: dev

spring:
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  port: 8880
  tomcat:
    max-connections: 20000
#    threads:
#      max: 600
#      min-spare: 100
cors:
  origins:
    - http://localhost*
    - https://localhost*
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
