#spring.profiles.active: dev

spring:
  config:
    import: optional:file:.env[.properties]
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${STORAGE_DB_URL}
    username: root
    password: ${STORAGE_DB_PASS}
  data:
    redis:
      host: localhost
      port: ${REDIS_BINDING_PORT}
      password: ${REDIS_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8880/auth/login/naver
            scope:
              - name
              - email
              - age
              - birthday
              - phone
            client-authentication-method: basic

auth:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-exp: ${JWT_ACCESS_EXP}
    refresh-exp: ${JWT_REFRESH_EXP}
    issuer: ${JWT_ISSUER}

server:
  port: 8880
  tomcat:
    max-connections: 20000
#    threads:
#      max: 600
#      min-spare: 100
cors:
  origins:
    - http://localhost:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - HEAD
